### ISSUE TITLE
The tag name provided is not a valid name

### ISSUE THREAD

**Issue by pimmee** [jaredLunde/snowpack-plugin-svgr#5]
**Describe the bug**
I'm trying to style a svg with styled components but are running into issues.

**To Reproduce**

1. Install snowpack and follow the instructions of this repository.
2. import Logo from 'assets/logo.svg';
3. Try to style a svg with styled components
`const StyledLogo = styled(Logo)({
  display: 'block',
  margin: '0 auto',
  position: 'relative',
  width: 56,
  height: 56
});`

**Expected behavior**
To be able to use it as a react component like you do [in create-react-app](https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs).
`import { ReactComponent as Logo } from './logo.svg';`

**Screenshots**
![image](https://user-images.githubusercontent.com/33460567/104657881-102d9900-56c2-11eb-8ef2-33c37083b109.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 86

**Comment by fgblomqvist** [comment]
I'm getting this same error, but I'm not using styled components, just importing the svg. Why was this issue closed without a comment @jaredLunde?

**Comment by jaredLunde** [comment]
Oh, because the library works for me as advertised and I'm not a support line

**Comment by fgblomqvist** [comment]
I don't think anyone expects you to be the support line, but you could always just say things like "It works as intended for me, so please provide a minimal repo that reproduces this, otherwise it's too hard to know if it's a bug or not" 🙂 .
Either way, for anyone else that cares, this is the output I get when I do a Snowpack build:

logo.svg.proxy.js
```js
export default "/_snowpack/pkg/randompackage/logos/logo.svg";
```
I would expect this file to hold the converted SVG, but perhaps this plugin can't handle external SVGs 🤷
